// <auto-generated />
using System;
using CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Migrations
{
    [DbContext(typeof(StudentsDbContext))]
    [Migration("20240923111752_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentCode = "CS1234",
                            DepartmentName = "ComputerScience"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentCode = "MTH567",
                            DepartmentName = "Mathematics"
                        });
                });

            modelBuilder.Entity("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.DepartmentLecture", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("LectureId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId", "LectureId");

                    b.HasIndex("LectureId");

                    b.ToTable("DepartmentsLectures", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            LectureId = 1
                        },
                        new
                        {
                            DepartmentId = 1,
                            LectureId = 2
                        },
                        new
                        {
                            DepartmentId = 2,
                            LectureId = 3
                        });
                });

            modelBuilder.Entity("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.Lecture", b =>
                {
                    b.Property<int>("LectureId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LectureId"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("LectureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("LectureId");

                    b.ToTable("Lectures", (string)null);

                    b.HasData(
                        new
                        {
                            LectureId = 1,
                            Duration = new TimeSpan(0, 11, 30, 0, 0),
                            LectureName = "Algorithms",
                            Time = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            LectureId = 2,
                            Duration = new TimeSpan(0, 13, 30, 0, 0),
                            LectureName = "Calculus",
                            Time = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            LectureId = 3,
                            Duration = new TimeSpan(0, 15, 30, 0, 0),
                            LectureName = "DataStructures",
                            Time = new TimeSpan(0, 14, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("StudentId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DepartmentId = 1,
                            Email = "john.smith@example.com",
                            LastName = "Smith",
                            Name = "John",
                            StudentCode = "12345678"
                        },
                        new
                        {
                            StudentId = 2,
                            DepartmentId = 2,
                            Email = "alice.johnson@example.com",
                            LastName = "Johnson",
                            Name = "Alice",
                            StudentCode = "87654321"
                        });
                });

            modelBuilder.Entity("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.StudentLecture", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("LectureId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "LectureId");

                    b.HasIndex("LectureId");

                    b.ToTable("StudentLectures", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            LectureId = 1
                        },
                        new
                        {
                            StudentId = 1,
                            LectureId = 3
                        },
                        new
                        {
                            StudentId = 2,
                            LectureId = 2
                        });
                });

            modelBuilder.Entity("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.DepartmentLecture", b =>
                {
                    b.HasOne("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.Department", "Department")
                        .WithMany("DepartmentLectures")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.Lecture", "Lecture")
                        .WithMany("DepartmentLectures")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.Student", b =>
                {
                    b.HasOne("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.StudentLecture", b =>
                {
                    b.HasOne("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.Lecture", "Lecture")
                        .WithMany("StudentLectures")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.Student", "Student")
                        .WithMany("StudentLectures")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.Department", b =>
                {
                    b.Navigation("DepartmentLectures");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.Lecture", b =>
                {
                    b.Navigation("DepartmentLectures");

                    b.Navigation("StudentLectures");
                });

            modelBuilder.Entity("CS_EF_Atsiskaitymas_Studentu_Informacine_Sistema.Entities.Student", b =>
                {
                    b.Navigation("StudentLectures");
                });
#pragma warning restore 612, 618
        }
    }
}
